GET https://marketing.ishpejti.al/api/bot
Content-Type: application/json

{"object":"whatsapp_business_account","entry":[{"id":"100294836365689","changes":[{"value":{"messaging_product":"whatsapp","metadata":{"display_phone_number":"355696755067","phone_number_id":"113312888381594"},"statuses":[{"id":"wamid.HBgNMjM0NzAxNjc5MTUxMhUCABEYEkQ0NzA4NDFCOTFGRjRFMjBBRAA=","status":"read","timestamp":"1680968271","recipient_id":"2347016791512"}]},"field":"messages"}]}]}